controller_manager:
  ros__parameters:
    update_rate: 30

    alfred_diff_cont:
      type: diff_drive_controller/DiffDriveController

    alfred_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

alfred_diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 30

    base_frame_id: alfred_base_link
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.3 # need to be tuned
    wheel_radius: 0.05 # need to be tuned

    # wheel_separation_multiplier: 1.0
    # left_wheel_radius_multiplier: 1.0
    # right_wheel_radius_multiplier: 1.0

    # odom_frame_id: odom

    # open_loop: true
    # enable_odom_tf: true

    # cmd_vel_timeout: 0.5
    use_sim_time: true

    # use_stamped_vel: true

alfred_joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    interfaces: ["position", "velocity"]
    joints: ["left_wheel_joint", "right_wheel_joint"]
