controller_manager:
  ros__parameters:
    update_rate: 150 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    xarm7_traj_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    alfred_diff_cont:
      type: diff_drive_controller/DiffDriveController

    alfred_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

xarm7_traj_controller:
  ros__parameters:
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.0
      joint1: { trajectory: 1.0, goal: 0.01 }
      joint2: { trajectory: 1.0, goal: 0.01 }
      joint3: { trajectory: 1.0, goal: 0.01 }
      joint4: { trajectory: 1.0, goal: 0.01 }
      joint5: { trajectory: 1.0, goal: 0.01 }
      joint6: { trajectory: 1.0, goal: 0.01 }
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0

alfred_diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 50.0

    base_frame_id: base_center
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.3 # need to be tuned
    wheel_radius: 0.05 # need to be tuned

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom

    open_loop: true
    enable_odom_tf: true

    # cmd_vel_timeout: 0.5
    # use_sim_time: true

    use_stamped_vel: false

alfred_joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    interfaces: ["position", "velocity"]
    joints: ["left_wheel_joint", "right_wheel_joint"]
