/oak:
  ros__parameters:
    camera:
      i_nn_type: none
      i_pipeline_type: Depth
    right:
      i_publish_topic: true
    stereo:
      i_extended_disp: true
      # i_align_depth: true
      # i_enable_spatial_filter: true
      i_enable_speckle_filter: true
      i_speckle_filter_range: 100
      i_enable_decimation_filter: true
      i_stereo_conf_threshold: 220
      i_enable_threshold_filter: true
      i_threshold_filter_min_range: 220
      i_threshold_filter_max_range: 2000
